name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # 或 master，根据你的主分支名称

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: true  # 拉取主题子模块

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.146.5'

      - name: Build
        run: hugo --minify --theme hugo-theme-stack

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages  # 明确指定推送到 gh-pages 分支